### ISSUE TITLE
Osscameroon blog improvement

### ISSUE THREAD

**Issue by guediagael** [osscameroon/Open-Projects#10]
# PROJECT IDEA
Have a better text editor for the blog project

## Introduction
Provide an interface (WordPress?) to allow a publisher to have a better user experience when publishing to osscameroon blog.

## Why ?
The current interface only provides a markdown editor, which is not convenient for articles with multimedia (external embedded). It could limit the way publishers provide graphical explanations in their articles. 

## Description
We could use WordPress for example or any other plugins/frameworks to provide an easy and rich interface for blogging. This article explains how one can reproduce Medium experience on their own WordPress blogging site
[https://blog.prototypr.io/how-i-cloned-medium-blog-design-on-my-website-12be12d080b7](url). Could be a good starting point for brainstorming.

## Labels
#web #ux 

## License

[MIT](https://choosealicense.com/licenses/mit/)

**Comment by elhmn** [comment]
Thank you for suggesting this, as I said in the telegram chat it seems to me that using a markdown format + hugo is the easiest way for us to handle the blog editing in open source.

I will close this issue as it does not seem to be easily manageable and requires more resources to implement than we currently have. Also nobody writes articles yet 😄 , so it is not really worth the effort
