### ISSUE TITLE
Implementation of quantum computing community

### ISSUE THREAD

**Issue by w4b4l** [osscameroon/Open-Projects#19]
# PROJECT IDEA

Hello, I'm looking for People quantum computing enthusiast.

## Introduction

Quantum computing is a new trend in the 4th industrial revolution. It's an opportunity for young or old scientist willing to develop the field of computing using new paradigm while evolving.

## Why ?

I need people good in computing, math and physics. We'll develop our own computer or design that will enable us to master the field in Africa and maybe open new opportunities.

## Description

The main idea as presented earlier is to build our own quantum computing unit and if It's possible build a physical one even if It's too expensive. WE can develop algorithms linked to this New computing technic while developing machine learning or enhancing cybersecurity as planned. Many resources are available for it.

## Labels

We will develop using physics, maths and quantum mechanics principles all the different tools planned. It will be hard to find resources that will help, but we will be using IBM Qiskit platform and other resource available from studies. 
Any idea will be welcome and Never think that you have a Bad idea.

## License

[MIT](https://w4b4l-quantumcomputing.com/licenses/mit/)

**Comment by SalathielGenese** [comment]
Hi,

I good at computing, have done maths for some time now and have never been good at physics. But still... I have strong interest in were the quantum computing is going (been reading news for +5 years now).

Do I qualify to join?

**Comment by w4b4l** [comment]
indeed you are qualified. There are many resources available for you to meet the criteria needed
Just get in touch

**Comment by elhmn** [comment]
Closing as it is out of the scope of what our community can provide at the moment. A separate community needs to be created for that purpose
